name: ClashRealms
version: 1.0
main: com.guildwars.GuildWarsPlugin
api-version: 1.20
commands:
  guild:
    description: Base command for guild operations
    usage: /guild <create|invite|declarewar|claim|siege|koth|info|top>
    permission: guildwars.command.guild
  gc:
    description: Sends a message to your guild chat.
    usage: "/gc <message>"
    aliases: [guildchat]
    permission: guildwars.command.gc # Optional: define a permission
permissions:
  guildwars.command.guild:
    default: true
